baseURL: 'https://chiru-27.github.io/chiranjiv-portfolio'
languageCode: 'en-us'
title: 'Chiranjiv Gawande - Bioinformatician & Computational Biology Researcher'

# Hugo Modules
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

# Markup
markup:
  goldmark:
    renderer:
      unsafe: true

# Security
security:
  enableInlineShortcodes: false
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_

# Related
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
